# Copyright 2018-2021 Rahul De
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02

    steps:
      - checkout

      - run:
          name: Git clean slate
          command: rm -rf ~/.gitconfig

      - run:
          name: Setup Babashka
          command: |
            curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
            sudo bash install

      - run:
          name: Setup Clojure
          command: |
            curl -sLO https://download.clojure.org/install/linux-install.sh
            sudo bash linux-install.sh

      - restore_cache:
          keys:
            - bob-v1-

      - run:
          name: Prep all deps
          command: bb prep

      - save_cache:
          key: bob-v1-{{ checksum "apiserver/deps.edn" }}-{{ checksum "entities/deps.edn" }}-{{ checksum "runner/deps.edn" }}-{{ checksum "common/deps.edn" }}
          paths:
            - ~/.m2
            - ~/.gitlibs

      - run:
          name: Run all tests
          command: bb test

      - run:
          name: Build executables
          command: bb compile

      - run:
          name: Build images
          command: bb image

      - run:
          name: Publish images
          command: echo ${GHCR_TOKEN} | docker login ghcr.io --username lispyclouds --password-stdin && bb push
